Signup form
lablueprint/apifm-mobile-app pull request #10
Opened 2022-02-23 21:53 UTC by glm1550

Has functionality of signup form and follows rough guidelines of figma. Pushes successfully to airtable, and error checks input values. next pr will be to match figma visuals

2022-03-21 18:24 UTC, glm1550 commented
functionality and matches figma. note: back button on second page to be replaced once design finalizes back button (functional placeholder for now)

2022-03-27 07:21 UTC, curesh requested changes
Wow this feature looks super neat, thanks for all your hard work! Your code writing is also clean and easy to review so great job with that too. I've included a few comments about some styling issues, but since this is lofi try your best to make it work but if its taking too long then don't worry too much about it. We can handle those once the hifi designs come out.

After you fix these comments, push another commit and I'll approve the PR. Great work, Grace!

2022-03-27 07:21 UTC, curesh commented on src/Navigation/StackNavigation.js
>  import SignInScreen from '../SignIn/SignInScreen';
Can you rename these screens and folders to be signup instead of signin? Also, can you rename the two components SignInScreen, SignInScreen2 to be more reflective of their function; ie. SignUpScreen, SignUpConfimationScreen

2022-03-27 07:21 UTC, curesh commented on src/SignIn/SignInScreen.js
> +  text: {
Can you add some padding to the textbox, so there is more gap on the left for the placeholder text and the actual text?

2022-03-27 07:21 UTC, curesh commented on src/SignIn/SignInScreen.js
>    const [firstName, setFirstName] = useState('');
I think its ok for this, but another option for future features is to use a single variable of type object as the state variable, where the object has various parameters of firstName, lastName, etc.

Then, you only need one state variable instead of 15.

2022-03-27 07:21 UTC, curesh commented on src/SignIn/SignInScreen.js
> +
Delete extra newlines

2022-03-27 07:21 UTC, curesh commented on src/SignIn/SignInScreen.js
> +      <View style={styles.text}>
Can you center align this text like the figma

2022-03-27 07:21 UTC, curesh commented on src/SignIn/SignInScreen.js
> +        <View style={styles.inputs}>
The order for some of the textboxes are different from the figma– can you move around these view tags to match it?

2022-03-27 07:21 UTC, curesh commented on src/SignIn/SignInScreen2.js
> +// import React from 'react';
Remove unnecessary comments, throughout file

2022-03-27 07:21 UTC, curesh commented on src/SignIn/SignInScreen2.js
> +    // marginTop: 10,
Remove unnecessary comments

2022-03-27 07:21 UTC, curesh commented on src/SignIn/SignInScreen.js
> +      <Text style={styles.text}>Delivery Address</Text>
Increase font weight to match figma

2022-03-27 07:21 UTC, curesh commented on src/SignIn/SignInScreen.js
> +            name={hidePass ? 'eye-slash' : 'eye'}
pretty cool stuff grace

2022-03-27 07:21 UTC, curesh commented on src/SignIn/SignInScreen.js
> +    // width: 330,
remove unnecessary comments throughout file

2022-03-27 07:21 UTC, curesh commented on src/SignIn/SignInScreen.js
> +      <View style={styles.inputs}>
Can you do input validation to make sure zipcode is a number

2022-04-05 04:58 UTC, hwang635 commented on src/SignUp/SignInScreen.js
> +          Alert.alert(err, err.message);
Change this to Alert.alert(err.error, err.message) to get rid of the ReadableNativeMap error

2022-04-05 05:00 UTC, hwang635 commented on src/SignUp/SignInScreen.js
> +            organization,
some of these field names have been changed in airtable

2022-04-23 03:10 UTC, hwang635 commented on src/SignUp/SignInScreen.js
> +    // console.log(text);
remove console.log/commented out things

2022-04-23 03:10 UTC, hwang635 commented on src/SignUp/SignInScreen.js
> +      // console.log('Email is Not Correct');
remove console.logs

2022-04-23 03:11 UTC, hwang635 commented on src/SignUp/SignInScreen.js
> +    const match = cleaned.match(/^(1|)?(\d{3})(\d{3})(\d{4})$/);
it was a really good idea to use regex

2022-04-23 03:11 UTC, hwang635 commented on src/SignUp/SignInScreen.js
> +        Alert.alert('Please enter a valid phone number');
can you specify that a valid phone number must be 10 digits?

2022-04-23 03:12 UTC, hwang635 commented on src/SignUp/SignInScreen.js
> +    } else if (zip === '' || isNaN(zip) || (zip.length !== 5)) {
this is really thorough validation!

2022-04-23 03:18 UTC, hwang635 requested changes
The sign up stuff looks really good, you have really thorough validation for everything. Your code is also really clean. There are a few comments/console.logs that should be removed but otherwise it's ready for merge. Thanks Grace!

2022-04-23 03:18 UTC, hwang635 commented on src/SignUp/SignInScreen.js
> +          // Alert.alert(err, err.message);
remove commented out things

2022-04-26 05:07 UTC, hwang635 approved these changes
Thanks Grace! It looks great.

2022-04-26 05:07 UTC, merged