Helen contactscreen
lablueprint/apifm-mobile-app pull request #19
Opened 2022-04-08 01:13 UTC by hwang635

Finished lofi contact screen
- Form takes in user input, submits if all fields are filled (if not filled, alerts with an error message), and airtable automatically sends email with the form input
- Icons lead to APIFM's website, facebook, and instagram

TODO: revisit when jeff's menu is added for small spacing fix

2022-04-12 05:51 UTC, he-is-james requested changes
overall, great work!

2022-04-12 05:51 UTC, he-is-james commented on src/ContactScreen.js
> +      <TextInput
This section should validate that the input is an email
https://reactnative.dev/docs/textinput
`keyboardType="email-address"` is a to have

2022-04-12 05:51 UTC, he-is-james commented on src/ContactScreen.js
> +    textAlignVertical: 'top', // prevent text from going to the centre
remove comments

2022-04-14 01:20 UTC, hwang635 commented on src/ContactScreen.js
> +    textAlignVertical: 'top', // prevent text from going to the centre
this is a useful comment/for future ref lol

2022-04-15 21:07 UTC, he-is-james commented on src/ContactScreen.js
> +    textAlignVertical: 'top', // prevent text from going to the centre
oh whoops lol

2022-04-15 21:17 UTC, he-is-james approved these changes

2022-04-16 00:48 UTC, merged