HiFi Hamburger Menu pt. 2
lablueprint/apifm-mobile-app pull request #26
Opened 2022-04-26 05:29 UTC by thejefflu

CHANGED:
- implemented hi-fi designs
- added log out and close drawer buttons

TODO:
- airtable functionality (wait for profile screen to be completed?)
- route "past orders" and "log out" options to proper screens (once their respective screens are completed)

2022-04-30 00:54 UTC, hwang635 commented on src/Navigation/CustomDrawer.js
> +            style={{
move long styles to stylesheet

2022-04-30 00:54 UTC, hwang635 commented on src/Navigation/CustomDrawer.js
> +            style={{
move long styles to stylesheet

2022-04-30 00:56 UTC, hwang635 commented on src/Navigation/CustomDrawer.js
> +    <View style={{
change the fonts please!

2022-04-30 00:57 UTC, hwang635 requested changes
Hi Jeff! This looks really nice. Only things to do seem to be the fonts and stylesheet. I can't run this on my own emulator but I'm going to come back to it later to see if there's a serious issue.

2022-05-05 06:39 UTC, curesh commented
Note that code only worked after following these two stackoverflows.
- https://stackoverflow.com/questions/67130651/reanimated-2-failed-to-create-a-worklet-maybe-you-forgot-to-add-reanimateds-ba
- https://stackoverflow.com/questions/46878638/how-to-clear-react-native-cache

2022-05-05 06:40 UTC, curesh commented
Also, log out button throws an error. Ideally we want it to just not work (be greyed out), since we havent implementing logging out functionality yet.

2022-05-05 06:42 UTC, merged