Hifi signup
lablueprint/apifm-mobile-app pull request #29
Opened 2022-05-03 00:25 UTC by glm1550

2022-05-07 01:10 UTC, curesh requested changes
Hi Grace this feature is gorgeous thank for your hard work uwu
I added a few syntax, code cleanliness comments but otherwise looks good. Feel free to merge it after you fix those issues. Great stuff!

2022-05-07 01:10 UTC, curesh commented on src/Navigation/StackNavigation.js
> +    <stackNavig.Navigator initialRouteName="Log In">
Why is the inital route set to log in, instead of landing page

2022-05-07 01:10 UTC, curesh commented on src/SignUp/LoginScreen.js
> +    // color: '#1D763C',
Remove unnecessary comments like this and similar ones below

2022-05-07 01:10 UTC, curesh commented on src/SignUp/LoginScreen.js
>    container: {
I don't think this is used, can you remove it

2022-05-07 01:10 UTC, curesh commented on src/SignUp/LoginScreen.js
> +  backgroundimage: {
Make this camelCase

2022-05-07 01:10 UTC, curesh commented on src/SignUp/SignInScreen.js
>  import React, { useState, useRef } from 'react';
Can you rename this file to SignUpScreen instead of SignIn...

2022-05-07 01:10 UTC, curesh commented on src/SignUp/SignInScreen.js
>  import React, { useState, useRef } from 'react';
and the other one too

2022-05-07 01:10 UTC, curesh commented on src/SignUp/LoginScreen.js
> +          {/* <Icon icon="ant-design:user-outlined" /> */}
Remove excess comments

2022-05-07 01:10 UTC, curesh commented on src/SignUp/SignInScreen.js
> +    // backgroundColor: '#FFFFFF',
remove
comment

2022-05-10 05:36 UTC, glm1550 commented
Hifi version of signup. Signup feature not yet implemented - covered in future sprint.

2022-05-14 02:16 UTC, merged