Signup form
lablueprint/apifm-mobile-app pull request #4
Opened 2022-01-15 03:17 UTC by he-is-james

uses next-input-field
incorporates Config but unsure that it works since it didn't work on my system
otherwise, pressing return on finishing a field moves to the next and pressing the submit button creates a user on the airtable form

2022-01-16 00:09 UTC, hwang635 commented on android/app/src/main/java/com/apifm/MainApplication.java
> +import com.lugg.ReactNativeConfig.ReactNativeConfigPackage;
can you remove these changes / this file

2022-01-16 00:11 UTC, hwang635 commented on android/settings.gradle
> +include ':react-native-config'
duplicate lines here

2022-01-16 00:12 UTC, hwang635 commented on src/SignIn/SignInScreen.js
> +    // console.log(firstName);
remove these comments

2022-01-16 00:14 UTC, hwang635 commented on src/SignIn/SignInScreen.js
> +        console.error(err);
Can you replace the console.log statements with an alert/etc that shows up on screen?

2022-01-16 00:15 UTC, hwang635 commented on src/SignIn/SignInScreen.js
> +        console.log(record.getId());
Same as above, we don't want to keep console.log statements bc they can accumulate and be confusing for devs if you don't know where they originate and they don't give any error info to the user

2022-01-16 00:15 UTC, hwang635 commented on src/SignIn/SignInScreen.js
> +        <Icon
The hide password fx is super cool

2022-01-16 00:18 UTC, hwang635 requested changes
This looks really good! Please get react native config fixed if you haven't (I added steps in the env setup doc) and there are some minor edits to make that I commented on, but overall you did great work and everything looks super nice. Thanks James and Grace for your attention to detail and getting it done so fast!

2022-01-21 09:17 UTC, hwang635 requested changes
This looks great! One last thing -- can you add a check so that the sign up button can't be pressed/the form can't submitted unless the user has filled out all information? An alert that the user can't submit because of missing info would be great also so that they're not confused why it's not working. Right now the form can be submitted even if there's no information entered, which makes it possible to fill the airtable up with random empty rows or have a user with missing data.

2022-01-25 07:29 UTC, glm1550 commented
the form now checks if fields are populated for valid submission

2022-01-29 02:12 UTC, hwang635 commented on src/SignIn/SignInScreen.js
> +    else if (email== ""){
The == should be "==="

2022-01-29 02:12 UTC, hwang635 commented on src/SignIn/SignInScreen.js
> +      {/* <Title style={styles.titleText}> SignInScreen  :) </Title>
Remove commented out stuff

2022-01-29 02:14 UTC, hwang635 commented on src/SignIn/SignInScreen.js
> +    if (firstName == ""){
This looks good but I don't think it passes eslint, make sure estlint is working in your env and don't push before checking that everything passes please!

2022-01-29 02:35 UTC, hwang635 commented on src/SignIn/SignInScreen.js
> +          alert(err);
Can this be an Alert.alert like the ones above?

2022-01-29 02:38 UTC, hwang635 requested changes
Hi Grace and James! Thanks for adding a submission check, everything looks pretty good. There are some minor edits to make and please pull from master to resolve merge conflicts; then it should be good to merge.

2022-01-29 03:05 UTC, hwang635 approved these changes
Beautiful thanks for working on this!

2022-01-29 03:06 UTC, merged