Cart Checkout Confirmation Screen
lablueprint/apifm-mobile-app pull request #9
Opened 2022-02-19 03:53 UTC by ashi72

besides the confirmation screen, also added two buttons for navigating to the checkout screen and changed the stack navigator; also installed some new packages like one for icons (react native vector icons);

2022-03-08 01:14 UTC, curesh requested changes
Wow this feature is so clean, the styling looks almost exactly like the figma! Your code is also super clean as always. I've added a few comments about general syntactical stuff, and removing unneeded comments. Also could you add the place order button at the bottom, and remove the market button (since it does the same thing). Otherwise, great work and I'm looking forward to seeing what else you're gonna do this year!

2022-03-08 01:14 UTC, curesh commented on index.js
> +console.log(Config.REACT_APP_AIRTABLE_BASE_KEY);
Can we remove this line, and also the import above

2022-03-08 01:14 UTC, curesh commented on src/Checkout/CheckoutScreen.js
> +    // marginLeft: '2%',
Remove unneeded comments here and in the rest of the file

2022-03-08 01:14 UTC, curesh commented on src/Checkout/CheckoutScreen.js
> +  topIcon: {
Remove since its not used

2022-03-08 01:14 UTC, curesh commented on src/Profile/ProfileScreen.js
> +    // base('Users').select({
Remove comments that you dont need

2022-03-08 01:14 UTC, curesh commented on src/Profile/ProfileScreen.js
> +      });
Add error handler for airtable call, and do something like "Alert.alert(err.message);" inside of it

2022-03-08 01:14 UTC, curesh commented on src/Checkout/CheckoutScreen.js
> +  const calcTotal = () => {
Modify this so it takes in a parameter user email variable, and plugs that into the airtable call

2022-03-08 01:14 UTC, curesh commented on src/Checkout/CheckoutScreen.js
> +      filterByFormula: '{email} = "helen@gmail.com"',
modify this to use the same email variable as above, and define this at the top of the function

2022-03-08 01:14 UTC, curesh commented on src/Checkout/CheckoutScreen.js
> +      filterByFormula: '{user_id} = "helen@gmail.com"',
same thing as above

2022-03-08 01:14 UTC, curesh commented on src/Checkout/CheckoutScreen.js
> +        marginTop: '8%', marginHorizontal: '8%', marginBottom: '4%', borderBottomColor: 'grey', borderBottomWidth: 2,
Move the styling attributes into the subcontainer thing in the stylesheet

2022-03-08 01:14 UTC, curesh commented on src/Checkout/CheckoutScreen.js
> +        <Text style={[styles.title, { fontWeight: '700', marginLeft: '0%', marginBottom: '0%' }]}>
same as above

2022-03-08 01:14 UTC, curesh commented on src/Checkout/CheckoutScreen.js
> +          onPress={() => navigation.navigate('Marketplace')}
Add a place order button instead of the buy tbd

2022-04-09 09:54 UTC, ashi72 commented on src/Checkout/CheckoutScreen.js
> +        marginTop: '8%', marginHorizontal: '8%', marginBottom: '4%', borderBottomColor: 'grey', borderBottomWidth: 2,
even if its just used once?

2022-04-09 10:09 UTC, closed without merging

2022-04-09 10:10 UTC, ashi72 commented
mostly done! not sure about the subcontainer styling header if its a one time specification and theres other subcontainers with different specifications? also went back and fixed issues from the profile screen pr hehe